// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_perhand p_perhand;
        
        private static SteamVR_Input_ActionSet_mirrored p_mirrored;
        
        public static SteamVR_Input_ActionSet_perhand perhand
        {
            get
            {
                return SteamVR_Actions.p_perhand.GetCopy <SteamVR_Input_ActionSet_perhand>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mirrored mirrored
        {
            get
            {
                return SteamVR_Actions.p_mirrored.GetCopy <SteamVR_Input_ActionSet_mirrored>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_perhand = ((SteamVR_Input_ActionSet_perhand)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_perhand>("/actions/perhand")));
            SteamVR_Actions.p_mirrored = ((SteamVR_Input_ActionSet_mirrored)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_mirrored>("/actions/mirrored")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[]
            {
                    SteamVR_Actions.perhand,
                    SteamVR_Actions.mirrored};
        }
    }
}
