// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_perhand_PoseRightHand;
        
        private static SteamVR_Action_Skeleton p_perhand_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_perhand_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p_perhand_HeadsetOnHead;
        
        private static SteamVR_Action_Pose p_perhand_PoseLeftHand;
        
        private static SteamVR_Action_Vector2 p_perhand_Move;
        
        private static SteamVR_Action_Vector2 p_perhand_Rotate;
        
        private static SteamVR_Action_Boolean p_perhand_Jog;
        
        private static SteamVR_Action_Boolean p_perhand_NextPage;
        
        private static SteamVR_Action_Boolean p_perhand_PreviousPage;
        
        private static SteamVR_Action_Boolean p_perhand_Cancel;
        
        private static SteamVR_Action_Boolean p_perhand_UIUp;
        
        private static SteamVR_Action_Boolean p_perhand_UIDown;
        
        private static SteamVR_Action_Boolean p_perhand_Recenter;
        
        private static SteamVR_Action_Boolean p_perhand_Grip;
        
        private static SteamVR_Action_Boolean p_perhand_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_perhand_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_perhand_Teleport;
        
        private static SteamVR_Action_Boolean p_perhand_StoreItem;
        
        private static SteamVR_Action_Boolean p_perhand_LocomotionAction;
        
        private static SteamVR_Action_Vibration p_perhand_Haptic;
        
        private static SteamVR_Action_Boolean p_mirrored_Radio;
        
        private static SteamVR_Action_Boolean p_mirrored_Interact;
        
        private static SteamVR_Action_Boolean p_mirrored_ToolPicker;
        
        public static SteamVR_Action_Pose perhand_PoseRightHand
        {
            get
            {
                return SteamVR_Actions.p_perhand_PoseRightHand.GetCopy <SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton perhand_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_perhand_SkeletonLeftHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton perhand_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_perhand_SkeletonRightHand.GetCopy <SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_perhand_HeadsetOnHead.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose perhand_PoseLeftHand
        {
            get
            {
                return SteamVR_Actions.p_perhand_PoseLeftHand.GetCopy <SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 perhand_Move
        {
            get
            {
                return SteamVR_Actions.p_perhand_Move.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 perhand_Rotate
        {
            get
            {
                return SteamVR_Actions.p_perhand_Rotate.GetCopy <SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_Jog
        {
            get
            {
                return SteamVR_Actions.p_perhand_Jog.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_NextPage
        {
            get
            {
                return SteamVR_Actions.p_perhand_NextPage.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_PreviousPage
        {
            get
            {
                return SteamVR_Actions.p_perhand_PreviousPage.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_Cancel
        {
            get
            {
                return SteamVR_Actions.p_perhand_Cancel.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_UIUp
        {
            get
            {
                return SteamVR_Actions.p_perhand_UIUp.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_UIDown
        {
            get
            {
                return SteamVR_Actions.p_perhand_UIDown.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_Recenter
        {
            get
            {
                return SteamVR_Actions.p_perhand_Recenter.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_Grip
        {
            get
            {
                return SteamVR_Actions.p_perhand_Grip.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_perhand_SnapTurnRight.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_perhand_SnapTurnLeft.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_Teleport
        {
            get
            {
                return SteamVR_Actions.p_perhand_Teleport.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_StoreItem
        {
            get
            {
                return SteamVR_Actions.p_perhand_StoreItem.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean perhand_LocomotionAction
        {
            get
            {
                return SteamVR_Actions.p_perhand_LocomotionAction.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration perhand_Haptic
        {
            get
            {
                return SteamVR_Actions.p_perhand_Haptic.GetCopy <SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean mirrored_Radio
        {
            get
            {
                return SteamVR_Actions.p_mirrored_Radio.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean mirrored_Interact
        {
            get
            {
                return SteamVR_Actions.p_mirrored_Interact.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean mirrored_ToolPicker
        {
            get
            {
                return SteamVR_Actions.p_mirrored_ToolPicker.GetCopy <SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    SteamVR_Actions.perhand_PoseRightHand,
                    SteamVR_Actions.perhand_SkeletonLeftHand,
                    SteamVR_Actions.perhand_SkeletonRightHand,
                    SteamVR_Actions.perhand_HeadsetOnHead,
                    SteamVR_Actions.perhand_PoseLeftHand,
                    SteamVR_Actions.perhand_Move,
                    SteamVR_Actions.perhand_Rotate,
                    SteamVR_Actions.perhand_Jog,
                    SteamVR_Actions.perhand_NextPage,
                    SteamVR_Actions.perhand_PreviousPage,
                    SteamVR_Actions.perhand_Cancel,
                    SteamVR_Actions.perhand_UIUp,
                    SteamVR_Actions.perhand_UIDown,
                    SteamVR_Actions.perhand_Recenter,
                    SteamVR_Actions.perhand_Grip,
                    SteamVR_Actions.perhand_SnapTurnRight,
                    SteamVR_Actions.perhand_SnapTurnLeft,
                    SteamVR_Actions.perhand_Teleport,
                    SteamVR_Actions.perhand_StoreItem,
                    SteamVR_Actions.perhand_LocomotionAction,
                    SteamVR_Actions.perhand_Haptic,
                    SteamVR_Actions.mirrored_Radio,
                    SteamVR_Actions.mirrored_Interact,
                    SteamVR_Actions.mirrored_ToolPicker};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.perhand_PoseRightHand,
                    SteamVR_Actions.perhand_SkeletonLeftHand,
                    SteamVR_Actions.perhand_SkeletonRightHand,
                    SteamVR_Actions.perhand_HeadsetOnHead,
                    SteamVR_Actions.perhand_PoseLeftHand,
                    SteamVR_Actions.perhand_Move,
                    SteamVR_Actions.perhand_Rotate,
                    SteamVR_Actions.perhand_Jog,
                    SteamVR_Actions.perhand_NextPage,
                    SteamVR_Actions.perhand_PreviousPage,
                    SteamVR_Actions.perhand_Cancel,
                    SteamVR_Actions.perhand_UIUp,
                    SteamVR_Actions.perhand_UIDown,
                    SteamVR_Actions.perhand_Recenter,
                    SteamVR_Actions.perhand_Grip,
                    SteamVR_Actions.perhand_SnapTurnRight,
                    SteamVR_Actions.perhand_SnapTurnLeft,
                    SteamVR_Actions.perhand_Teleport,
                    SteamVR_Actions.perhand_StoreItem,
                    SteamVR_Actions.perhand_LocomotionAction,
                    SteamVR_Actions.mirrored_Radio,
                    SteamVR_Actions.mirrored_Interact,
                    SteamVR_Actions.mirrored_ToolPicker};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[]
            {
                    SteamVR_Actions.perhand_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    SteamVR_Actions.perhand_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    SteamVR_Actions.perhand_PoseRightHand,
                    SteamVR_Actions.perhand_PoseLeftHand};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    SteamVR_Actions.perhand_HeadsetOnHead,
                    SteamVR_Actions.perhand_Jog,
                    SteamVR_Actions.perhand_NextPage,
                    SteamVR_Actions.perhand_PreviousPage,
                    SteamVR_Actions.perhand_Cancel,
                    SteamVR_Actions.perhand_UIUp,
                    SteamVR_Actions.perhand_UIDown,
                    SteamVR_Actions.perhand_Recenter,
                    SteamVR_Actions.perhand_Grip,
                    SteamVR_Actions.perhand_SnapTurnRight,
                    SteamVR_Actions.perhand_SnapTurnLeft,
                    SteamVR_Actions.perhand_Teleport,
                    SteamVR_Actions.perhand_StoreItem,
                    SteamVR_Actions.perhand_LocomotionAction,
                    SteamVR_Actions.mirrored_Radio,
                    SteamVR_Actions.mirrored_Interact,
                    SteamVR_Actions.mirrored_ToolPicker};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    SteamVR_Actions.perhand_Move,
                    SteamVR_Actions.perhand_Rotate};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    SteamVR_Actions.perhand_SkeletonLeftHand,
                    SteamVR_Actions.perhand_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[]
            {
                    SteamVR_Actions.perhand_HeadsetOnHead,
                    SteamVR_Actions.perhand_Move,
                    SteamVR_Actions.perhand_Rotate,
                    SteamVR_Actions.perhand_Jog,
                    SteamVR_Actions.perhand_NextPage,
                    SteamVR_Actions.perhand_PreviousPage,
                    SteamVR_Actions.perhand_Cancel,
                    SteamVR_Actions.perhand_UIUp,
                    SteamVR_Actions.perhand_UIDown,
                    SteamVR_Actions.perhand_Recenter,
                    SteamVR_Actions.perhand_Grip,
                    SteamVR_Actions.perhand_SnapTurnRight,
                    SteamVR_Actions.perhand_SnapTurnLeft,
                    SteamVR_Actions.perhand_Teleport,
                    SteamVR_Actions.perhand_StoreItem,
                    SteamVR_Actions.perhand_LocomotionAction,
                    SteamVR_Actions.mirrored_Radio,
                    SteamVR_Actions.mirrored_Interact,
                    SteamVR_Actions.mirrored_ToolPicker};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_perhand_PoseRightHand = ((SteamVR_Action_Pose)(SteamVR_Action.Create <SteamVR_Action_Pose>("/actions/perhand/in/PoseRightHand")));
            SteamVR_Actions.p_perhand_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/perhand/in/SkeletonLeftHand")));
            SteamVR_Actions.p_perhand_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create <SteamVR_Action_Skeleton>("/actions/perhand/in/SkeletonRightHand")));
            SteamVR_Actions.p_perhand_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/HeadsetOnHead")));
            SteamVR_Actions.p_perhand_PoseLeftHand = ((SteamVR_Action_Pose)(SteamVR_Action.Create <SteamVR_Action_Pose>("/actions/perhand/in/PoseLeftHand")));
            SteamVR_Actions.p_perhand_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/perhand/in/Move")));
            SteamVR_Actions.p_perhand_Rotate = ((SteamVR_Action_Vector2)(SteamVR_Action.Create <SteamVR_Action_Vector2>("/actions/perhand/in/Rotate")));
            SteamVR_Actions.p_perhand_Jog = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/Jog")));
            SteamVR_Actions.p_perhand_NextPage = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/NextPage")));
            SteamVR_Actions.p_perhand_PreviousPage = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/PreviousPage")));
            SteamVR_Actions.p_perhand_Cancel = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/Cancel")));
            SteamVR_Actions.p_perhand_UIUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/UIUp")));
            SteamVR_Actions.p_perhand_UIDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/UIDown")));
            SteamVR_Actions.p_perhand_Recenter = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/Recenter")));
            SteamVR_Actions.p_perhand_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/Grip")));
            SteamVR_Actions.p_perhand_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/SnapTurnRight")));
            SteamVR_Actions.p_perhand_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/SnapTurnLeft")));
            SteamVR_Actions.p_perhand_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/Teleport")));
            SteamVR_Actions.p_perhand_StoreItem = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/StoreItem")));
            SteamVR_Actions.p_perhand_LocomotionAction = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/perhand/in/LocomotionAction")));
            SteamVR_Actions.p_perhand_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create <SteamVR_Action_Vibration>("/actions/perhand/out/Haptic")));
            SteamVR_Actions.p_mirrored_Radio = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/mirrored/in/Radio")));
            SteamVR_Actions.p_mirrored_Interact = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/mirrored/in/Interact")));
            SteamVR_Actions.p_mirrored_ToolPicker = ((SteamVR_Action_Boolean)(SteamVR_Action.Create <SteamVR_Action_Boolean>("/actions/mirrored/in/ToolPicker")));
        }
    }
}
