// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mirrored : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Radio
        {
            get
            {
                return SteamVR_Actions.mirrored_Radio;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.mirrored_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToolPicker
        {
            get
            {
                return SteamVR_Actions.mirrored_ToolPicker;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jog
        {
            get
            {
                return SteamVR_Actions.mirrored_Jog;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.mirrored_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate
        {
            get
            {
                return SteamVR_Actions.mirrored_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.mirrored_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.mirrored_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.mirrored_Teleport;
            }
        }
    }
}
