// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.default_Interact;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseRightHand
        {
            get
            {
                return SteamVR_Actions.default_PoseRightHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseLeftHand
        {
            get
            {
                return SteamVR_Actions.default_PoseLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate
        {
            get
            {
                return SteamVR_Actions.default_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jog
        {
            get
            {
                return SteamVR_Actions.default_Jog;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToolPicker
        {
            get
            {
                return SteamVR_Actions.default_ToolPicker;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextPage
        {
            get
            {
                return SteamVR_Actions.default_NextPage;
            }
        }
        
        public virtual SteamVR_Action_Boolean PreviousPage
        {
            get
            {
                return SteamVR_Actions.default_PreviousPage;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cancel
        {
            get
            {
                return SteamVR_Actions.default_Cancel;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIUp
        {
            get
            {
                return SteamVR_Actions.default_UIUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIDown
        {
            get
            {
                return SteamVR_Actions.default_UIDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Recenter
        {
            get
            {
                return SteamVR_Actions.default_Recenter;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
